version: "3.0"

services:
  api:
    container_name: "api"
    volumes:
      - .:/app
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    tty: true

  client:
    container_name: "client"
    volumes:
      - .:/usr/src/app
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    tty: true